name: Deploy
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: ./package.json

      - name: Install dependencies
        run: pnpm install

  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: ESLint
        run: pnpm run lint

      - name: Prettier
        run: pnpm run prettier

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Type check
        run: pnpm run typecheck

  unit-tests:
    name: Vitest
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run unit tests
        run: pnpm run test

  e2e-tests:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifcact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: Playwright-report/
          retention-days: 30
